plugins {
	id 'com.android.application'
	id 'org.jetbrains.kotlin.android'
	id 'kotlin-android'
	id 'kotlin-kapt'
	id 'com.google.dagger.hilt.android'
	id 'io.realm.kotlin'
	id 'com.google.gms.google-services'
	id 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin'
	id 'com.google.android.gms.oss-licenses-plugin'
}

android {
	compileSdk 33

	defaultConfig {
		applicationId 'com.syncodec.graphite'
		minSdk 29
		targetSdk 33
		versionCode 26
		versionName '2.0.0'

		testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
		vectorDrawables {
			useSupportLibrary true
		}

		Properties properties = new Properties()
		if (rootProject.file('local.properties').exists()) {
			properties.load(rootProject.file('local.properties').newDataInputStream())
		}

		manifestPlaceholders.clientKey = properties.getProperty('CLIENT_KEY', '')
		manifestPlaceholders.mapsApiKey = properties.getProperty('MAPS_API_KEY', '')
		manifestPlaceholders.tmdbApiKey = properties.getProperty('TMDB_API_KEY', '')
		manifestPlaceholders.revenueCatApiKey = properties.getProperty('REVENUE_CAT_API_KEY', '')

		javaCompileOptions {
			annotationProcessorOptions {
			}
		}
	}

	buildTypes {
		release {
			minifyEnabled true
			shrinkResources true
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
//		debug {
//			minifyEnabled true
//			shrinkResources true
//			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
//		}
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_8
		targetCompatibility JavaVersion.VERSION_1_8
	}

	kotlinOptions {
		jvmTarget = '1.8'

		freeCompilerArgs += ["-Xjvm-default=all"]
	}

	buildFeatures {
		compose true
		buildConfig true
	}

	composeOptions {
		kotlinCompilerExtensionVersion compose_version
		kotlinCompilerVersion '1.5.30'
	}
	packagingOptions {
		resources {
			excludes += ['/META-INF/{AL2.0,LGPL2.1}', 'META-INF/DEPENDENCIES']
		}
	}

	kapt {
		correctErrorTypes true
	}

	namespace 'com.syncodec.graphite'
}

dependencies {

	implementation 'com.google.dagger:hilt-android:2.44.1'
	implementation 'androidx.work:work-runtime-ktx:2.8.0-rc01'
	implementation 'androidx.hilt:hilt-work:1.0.0'
	kapt 'com.google.dagger:hilt-compiler:2.44.1'

	implementation 'androidx.core:core-ktx:1.9.0'

	implementation 'androidx.activity:activity-compose:1.6.1'
	implementation 'androidx.appcompat:appcompat:1.7.0-alpha01'

	implementation 'androidx.compose.material:material:1.4.0-alpha03'
	implementation 'androidx.compose.material3:material3:1.1.0-alpha03'
	implementation 'androidx.compose.ui:ui:1.4.0-alpha03'
	implementation 'androidx.compose.foundation:foundation:1.3.1'
	implementation 'androidx.compose.ui:ui-tooling-preview:1.4.0-alpha03'
	implementation 'androidx.compose.ui:ui-util:1.4.0-alpha03'

	implementation 'androidx.work:work-runtime-ktx:2.8.0-rc01'
	implementation "androidx.glance:glance-appwidget:1.0.0-alpha05"

	implementation 'androidx.navigation:navigation-compose:2.5.3'
	implementation 'androidx.constraintlayout:constraintlayout-compose:1.0.1'

	implementation 'androidx.core:core-animation:1.0.0-beta01'

	implementation 'com.google.accompanist:accompanist-insets:0.27.0'
	implementation 'com.google.accompanist:accompanist-flowlayout:0.27.0'
	implementation 'com.google.accompanist:accompanist-pager:0.27.0'
	implementation 'com.google.accompanist:accompanist-systemuicontroller:0.27.0'
	implementation 'com.google.accompanist:accompanist-permissions:0.27.0'
	implementation 'com.google.accompanist:accompanist-webview:0.27.0'
	implementation 'com.google.accompanist:accompanist-swiperefresh:0.27.0'
	implementation 'com.google.accompanist:accompanist-navigation-animation:0.27.0'

	implementation 'org.burnoutcrew.composereorderable:reorderable:0.9.6'

	implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.5.1'
	implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1'
	implementation 'androidx.lifecycle:lifecycle-viewmodel-savedstate:2.5.1'
	implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.5.1'

	implementation "androidx.biometric:biometric-ktx:1.2.0-alpha05"

	implementation 'androidx.compose.runtime:runtime:1.3.2'

	implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4'
	implementation 'io.realm.kotlin:library-base:1.5.0'

	implementation 'androidx.room:room-runtime:2.4.3'
	implementation 'androidx.room:room-ktx:2.4.3'
	testImplementation 'androidx.room:room-testing:2.4.3'
	kapt 'androidx.room:room-compiler:2.4.3'
	kapt 'androidx.room:room-compiler:2.4.3'

	implementation 'com.fasterxml.jackson.core:jackson-core:2.14.0'
	implementation 'com.fasterxml.jackson.core:jackson-annotations:2.14.0'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.0'
	implementation 'com.fasterxml.jackson.module:jackson-module-kotlin:2.14.0'
//	implementation 'com.google.api-client:google-api-client-jackson2:2.1.1'

	implementation 'io.coil-kt:coil:2.2.2'
	implementation 'io.coil-kt:coil-compose:2.2.2'
	implementation 'io.coil-kt:coil-gif:2.2.2'
	implementation 'io.coil-kt:coil-video:2.2.2'

	implementation 'com.revenuecat.purchases:purchases:5.6.4'

	implementation platform('com.google.firebase:firebase-bom:31.0.3')
	implementation 'com.google.android.gms:play-services-auth:20.4.0'
	implementation 'com.google.firebase:firebase-analytics'
	implementation 'com.firebaseui:firebase-ui-auth:8.0.2'
	implementation 'com.google.firebase:firebase-auth-ktx'
	implementation 'com.google.firebase:firebase-storage-ktx'
	implementation 'com.google.firebase:firebase-firestore-ktx'
	implementation 'com.google.firebase:firebase-functions-ktx'

//	Google drive
//	implementation 'com.google.oauth-client:google-oauth-client-jetty:1.34.1'
//	implementation 'com.google.apis:google-api-services-drive:v3-rev20220815-2.0.0'
//	implementation 'com.google.api-client:google-api-client-android:1.20.0'

//	Dropbox
	implementation 'com.dropbox.core:dropbox-core-sdk:5.4.4'

	implementation 'com.squareup.okhttp3:okhttp:5.0.0-alpha.10'

	implementation 'joda-time:joda-time:2.12.1'

	implementation 'me.jorgecastillo:androidcolorx:0.2.0'
	implementation 'com.godaddy.android.colorpicker:compose-color-picker-android:0.5.1'

	implementation 'com.tobianoapps:bulletin:1.0.3'

	implementation 'org.apache.commons:commons-compress:1.20'
	implementation 'org.tukaani:xz:1.5'

//	implementation 'org.openjdk.nashorn:nashorn-core:15.4'
//	implementation 'javax.script:script:1.0'
// https://mvnrepository.com/artifact/org.mozilla/rhino
//	implementation 'org.mozilla:rhino:1.7.14'
//	implementation 'io.apisense:rhino-android:1.1.1'

	implementation 'com.google.android.play:core:1.10.3'

	implementation 'com.google.android.gms:play-services-location:21.0.1'
//	implementation 'com.google.maps.android:maps-ktx:3.4.0'
	implementation 'com.google.maps.android:maps-utils-ktx:3.4.0'

	implementation 'com.google.maps.android:maps-compose:2.7.2'
//	implementation 'com.google.maps.android:android-maps-utils-v3:2.4.0'
	implementation 'com.google.android.gms:play-services-maps:18.1.0'

	implementation 'androidx.datastore:datastore-preferences-core:1.0.0'
	implementation 'androidx.datastore:datastore-preferences:1.0.0'

	implementation "androidx.security:security-crypto:1.0.0"
	implementation "androidx.security:security-identity-credential:1.0.0-alpha03"
//	implementation "androidx.security:security-app-authenticator:1.0.0-alpha02"
//	androidTestImplementation "androidx.security:security-app-authenticator:1.0.0-alpha02"
//	implementation 'com.google.crypto.tink:tink-android:1.6.1'

	implementation 'com.valentinilk.shimmer:compose-shimmer:1.0.3'
	implementation "io.github.vanpra.compose-material-dialogs:datetime:0.8.1-rc"

//	implementation 'com.instabug.library:instabug:11.6.0'

	implementation 'com.github.skydoves:colorpicker-compose:1.0.0'
	implementation 'com.github.LucasFsc:Html2Pdf:0.2-beta'
	implementation 'io.noties.markwon:core:4.6.2'

	implementation 'com.github.Priyansh-Kedia:OpenGraphParser:2.5.5'

	implementation "com.google.android.gms:play-services-oss-licenses:17.0.0"


	implementation 'androidx.test:core-ktx:1.5.0'

	testImplementation 'junit:junit:4.13.2'

	androidTestImplementation 'androidx.test.ext:junit:1.1.4'
	androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0'
	androidTestImplementation 'androidx.compose.ui:ui-test-junit4:1.3.2'

	debugImplementation 'androidx.compose.ui:ui-tooling:1.3.2'
	debugImplementation 'androidx.compose.ui:ui-tooling-data:1.3.2'
	debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.10'
	androidTestImplementation 'androidx.compose.ui:ui-test-junit4:1.3.2'
	debugImplementation 'androidx.compose.ui:ui-test-manifest:1.3.2'
}
